### ISSUE TITLE
More accurate collisions/ Multi RayCast

### ISSUE THREAD

**Issue by eblabs** [adrenak/Tork#1]
Hi @adrenak,

Thanks for sharing this project! Really great work!

I was thinking of developing the wheel collider code to handle multiple raycasts per wheel (many more radiating from the center). How do you think this would work with the wheel script? I mean it looks like the wheel script is designed to only handle one hit point. Thanks for any thoughts on this!

**Comment by adrenak** [comment]
Glad you like the project!

Yes that was the idea initially but I went ahead with a single ray so that I can resume the development of the rest of my game without taking too much time on this.

If you have the time and interest to work on this please go ahead!

**Comment by byGui** [comment]
Hello,

First of all. Thanks @adrenak for sharing the project.

@eblabs I was thinking the same about the wheel collider. Maybe there's no need of more than one ray for all the games but it could be good to add width to the collider. I was thinking that adding the width value and how many rays do you want to test on each wheel could be nice.

**Comment by adrenak** [comment]
A parameter to specify the number of rays along width and radius would be great. Would improve the accuracy significantly when the wheel approaches steps or bumps. 

Games that are fine with a single ray can use 1 for both width and radial ray count.

**Comment by eblabs** [comment]
Hi,

Just setup a quick wheelcast script. Ill have to figure out how to combine these hit points into something usable by the wheel script....

![wheelCastTest](https://user-images.githubusercontent.com/5941510/56790210-cba8ee00-67b8-11e9-8612-005d3e300e50.gif)
![image](https://user-images.githubusercontent.com/5941510/56790226-dbc0cd80-67b8-11e9-93ca-22c77de17320.png)

**Comment by adrenak** [comment]
This looks great! I think a weighted average of raycast hit points, weighted by (L - D) where L is ray length and D is hit distance could give some good results.

This video here has some insights: https://youtu.be/SKXqWcaoTGE?t=263

**Comment by eblabs** [comment]
![brokenPhysics](https://user-images.githubusercontent.com/5941510/56854955-b84e6d80-68f3-11e9-9a9a-80f7e7e7ad69.gif)

Slightly comically broken, haha.
@adrenak, do you have any ideas what I'm doing wrong? Here's my fork:
https://github.com/eblabs/Tork

The one thing I'm not sure about is how to handle the hit distance. With the one ray solution its simpler and always directly in line with the wheel axis. In this situation, with multiple ray casts, the hit point can be off axis. Thanks for any ideas! (I hacked the wheelcast script into your wheel script, its a bit messy, but hopefully it makes sense.)

**Comment by eblabs** [comment]
I've tried to shoe-horn it in, but I think I'll try to strip the whole thing down and build it up piece by piece. It'll be more manageable that way. 

By all means, have a look though and let me know if you had any thoughts. 

More to come...

**Comment by eblabs** [comment]
Had a bit more success. Basically works, but its really unstable and could probably be simplified.
![kindaWorking](https://user-images.githubusercontent.com/5941510/56861269-24f95480-6954-11e9-9c0a-4ee2e2436ee9.gif)
![kindaWorking2](https://user-images.githubusercontent.com/5941510/56861347-c54f7900-6954-11e9-9da7-42c47c8d7010.gif)

**Comment by eblabs** [comment]
Had some more success, needed to rethink how the rays provide information about collisions. I didn't realize it at first, but the rays provide more information than just the contact point. They also project the full range of the suspension past the actual wheel radius. So I broke this process into two steps, first get the contact point at the radius, THEN calculate how this relates to the suspension range along the suspension axis. 

I have a couple of reservations about this method, it doesn't handle very fast landings at all, as the rays get stuck in the ground due to large movements between frames. Maybe having a "rim" collision object might help to avoid this. One other method would be to have a grid of rays projected from the top, this might produce more dependable results. More to come...

![working](https://user-images.githubusercontent.com/5941510/56876679-f33cc800-69fd-11e9-9253-144c22e0a641.gif)

**Comment by adrenak** [comment]
Thanks @eblabs , I'm out for a few days but I'll check out your fork once I'm back.

**Comment by eblabs** [comment]
![loopdeloop](https://user-images.githubusercontent.com/5941510/57432605-2f84db00-71eb-11e9-8bcb-090e0fd20edd.gif)
Sounds good @adrenak, I just did a bit of a house cleaning version which you can find here (https://github.com/eblabs/Tork). Im sure the coding style can use some improvements, but give it a try when you get a chance :)

![image](https://user-images.githubusercontent.com/5941510/57432950-06b11580-71ec-11e9-9c07-2730900bd05d.png)
Added a few options for toggling on/off 3D raycasts, and a few others. Span doesnt work yet...

**Comment by adrenak** [comment]
@eblabs this is awesome. I will definitely have a look. Exactly what a couple of people have been asking. Thanks!

**Comment by MarcusElg** [comment]
This would defently be a big improvement! Any update?

**Comment by eblabs** [comment]
@MCrafterzz , the update is available via the fork, hope that helps! I'm not sure if @adrenak is actively working on this anymore, I haven't been involved since May 2019 either.
https://github.com/eblabs/Tork

**Comment by ghost** [comment]
> @MCrafterzz , the update is available via the fork, hope that helps! I'm not sure if @adrenak is actively working on this anymore, I haven't been involved since May 2019 either. https://github.com/eblabs/Tork

Hi @eblabs  . This is really great job.  I would like to see a car suspension tutorial created by you. Is this possible?

**Comment by eblabs** [comment]
Hey, I'm no longer working on this either. Good luck!
