### ISSUE TITLE
RPM calculating

### ISSUE THREAD

**Issue by samserious25** [adrenak/Tork#7]
Hello qnd thanx for your physics, it is great! 

I usi rpm of wheels to make engine sound work. So it is possible eith unity's wheel colliders, but in Tork there is no rpm var on wheel.

So how can I get rpm?

**Comment by adrenak** [comment]
Hi, glad you like the project. You can calculate the rpm from the velocity and radius of the wheel. It is being done in the `SyncRotation` function in WheelRenderer.cs

If you add a Wheel.RPM property please send me a pull request, else I will do so in a few days.

Thanks

**Comment by samserious25** [comment]
I've done it. I'll send pull request little later
