### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by MarinoHappiness** [adrenak/Tork#9]
Hello,

The project fails to build in the latest Unity version with the following errors:

> Build completed with a result of 'Failed'
> UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:123)

> UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x00269] in /home/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:191 
>   at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /home/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:95 
> UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:123)

Unity version: 2019.3.6f1
OS: Linux Mint

Sincerely,
Marino

**Comment by adrenak** [comment]
Thanks for bringing to notice, I'll have a look at this later today

**Comment by adrenak** [comment]
Hi @MarinoHappiness , I've made a new commit fixing a bug during build. Please try now?
